FROM    mxnet/python:1.2.0-dev
MAINTAINER DavidFu <lexuszhi1990@gmail.com>
# build command:
# docker build --network host -t mxnet-ssd:v0.1 -f docker/Dockerfile.cpu.mx-1.2.0 .

RUN     pip3.6 install opencv-python matplotlib scipy graphviz tensorboardX

RUN     git clone https://github.com/lexuszhi1990/mxnet-ssd.git -b dist /app

WORKDIR /app
