FROM    mxnet/python:1.2.0-dev
MAINTAINER DavidFu <lexuszhi1990@gmail.com>

RUN     pip3.6 install opencv-python matplotlib scipy graphviz tensorboardX

RUN     git clone https://github.com/lexuszhi1990/mxnet-ssd.git -b dist /app

WORKDIR /app
