apiVersion: batch/v1
kind: Job
metadata:
  name: server
spec:
  template:
    metadata:
      name: server
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: mxnet:1.0.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /mnt/glusterfs
          name: glustervol
      volumes:
        - name: glustervol
          glusterfs:
            endpoints: glusterfs-cluster
            path: gv-test
            readOnly: false
      restartPolicy: Never
